# This workflow contains ...
# - test of the demo script
# - package build
# - package artifact upload

name: Test and build

# Controls when the action will run.
# Triggers the workflow on all push events
on:
  push:
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  test_and_build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v4

      # Sets up MATLAB on the GitHub Actions runner
      - name: Setup MATLAB
        uses: matlab-actions/setup-matlab@v2

      # run matlab script and execute demo as test
      - name: Test the execution of the demo script
        uses: matlab-actions/run-command@v2
        with:
          command: test

      # run matlab script and create the .mltbx file
      - name: Build the package
        uses: matlab-actions/run-command@v2
        with:
          command: build

      # add the .mltbx to a zip archive and upload this artifact. Note#1: there is currently no way to prevent the
      # double compression. For package releases, the .mltbx needs to be extracted from the zip file and added manually
      # to the GitHub release. Note#2: github.ref_name contains either the tag name (e.g. 'v1.2') or the branch name
      # ('main')
      - name: Upload package as artifact
        uses: actions/upload-artifact@v4
        with:
          name: remezex-${{ github.ref_name }}
          path: remezex*.mltbx
